# Generated by Django 3.1 on 2020-08-31 04:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orient', models.CharField(choices=[('ns', 'North South'), ('ew', 'East West')], max_length=2, verbose_name='orientation')),
                ('pair_num', models.IntegerField()),
                ('match_pts', models.IntegerField()),
            ],
            options={
                'ordering': ('orient', '-match_pts'),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='evening', max_length=10)),
                ('event', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date', 'time'),
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['club', '-date'], name='overtrick_s_club_2393c9_idx'),
        ),
        migrations.AddField(
            model_name='pair',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pair',
            name='player_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pair',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtrick.session'),
        ),
    ]
