# Generated by Django 3.1 on 2020-08-31 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('overtrick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('joined', models.DateField(default=datetime.date.today, verbose_name='date joined club')),
            ],
        ),
        migrations.AlterField(
            model_name='pair',
            name='player_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_as_a', to='overtrick.player'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='player_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_as_b', to='overtrick.player'),
        ),
    ]
