# Generated by Django 3.1 on 2020-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_subscriber_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date subscribed'),
        ),
    ]
